# version:
#   this specifies what version the config is set to, used for internal checks
# ban saving:
#   delay - how long to wait before starting to save bans [default: 900 == 5 minutes]
#   period - how long to go in between running the ban saver task [default: 5400 == 30 minutes]
# session pruning:
#   delay - how long to wait before starting the pruning task [default: 900 == 5 minutes]
#   period - how long to go in between running the task [default: 1800 == 10 minutes]
# wand-id:
#   this is the id of the admin wand item [default: 369 (blaze rod)]
# handler types: default, off, extended
#   default - uses the default handler for that action
#   off - turns off the handler
#   extended - modified 'default' state, allows setting of the handler by an outside plugin
#     for say, a plugin that extends this one by providing a separate set of handlers

version: 1.0
save-ban-delay: 900
save-ban-period: 5400
session-prune-delay: 900
session-prune-period: 1800
wand-id: 369
login-handler: default
whitelist-handler: off