# version:
#   this specifies what version the config is set to, used for internal checks [DO NOT TOUCH]
# override:
#   this options basically tells openauth that it can override bukkit's internal whitelisting and etc. [default: true]
# debug:
#   this tells openauth whether or not to print extra debug messages [default: false]
# metrics-enabled:
#   this tells the plugin whether or not to enable PluginMetrics [default: true]
# show-metrics-notice:
#   tells the controller whether or not to print the metrics usage notice on start of the plugin. [default: true]
# save-ban: (ban saving)
#   delay - how long to wait before starting to save bans [default: 6000 == 5 minutes]
#   period - how long to go in between running the ban saving task [default: 36000 == 30 minutes]
# save-whitelist: (whitelist saving)
#   delay - how long to wait before starting to save the whitelist [default: 18000 == 15 minutes]
#   period - how long to go in between running the whitelist saving task [default: 72000 == 60 minutes/1 hour]
# session-prune: (player session pruning)
#   delay - how long to wait before starting the pruning task [default: 6000 == 5 minutes]
#   period - how long to go in between running the task [default: 12000 == 10 minutes]
#   epsilon - how many sessions do i need to be inactive before i actually start pruning? [default: 3]
# wand-id:
#   this is the id of the admin wand item [default: 369 (blaze rod)]
# whitelist-handler: (handler types {default (true/on): true/on or false/off})
#   decides whether the respective handler is enabled or disabled [default: true]
# whitelisting:
#   broadcast-failures - when an unwhitelisted player attempts to join, broadcast it to all players [default: true]
#   print-on-load - print the whitelist when the whitelisting handler loads [default: true]
#   denial-message - what message to kick the unwhitelisted players with [default: You are not whitelisted on this server!]
# auth:
#   require - whether auth is required to be able to play, if so, user
#             will be frozen [default: true]
#   password-security - what type of password validating will be used? (basic or complex)
#             [default: basic]
#   greet-players - whether I will greet players upon "meeting" them. [default: true]
#   hide-inventory - do I hide the player's inventory before the identify? [default: false]
#   freeze-actions - actions that the player takes that will be
#                    frozen.
#     chat - freeze chat? [default: true]
#     commands - freeze all commands besides OA commands? [default: true]
#     drop - prevent players from dropping items? [default: true]
#     interact - freeze all player interactions? [default: true]
#     block-interact - freeze all block interactions? [default: true]
#     block-place - freeze all block placements? [default: true]
#     block-break - freeze all block breaks? [default: true]
#     movement - freeze all player movement? [default: false]
#     teleport - freeze player teleportation? [default: true]
# actions:
#   verbose-list - shows extra in /oa action list [default: false]
#   ban - settings for the ban action
#     kick - whether or not to kick the user when the ban action is used [default: true]
#   boom - settings for the boom action
#     fire - whether or not the explosion causes fire [default: false]
#     power - power of the explosion as a double [default: 2.0]
#     animal-cruelty - allows(true)/disallows(false) targeting of animals (cows, sheep, pigs, etc..)
#                        monsters will always be targetable. [default: false]
#     golem-cruelty - allows(true)/disallows(false) targeting of golems (snowmen, iron golems..)
#                        monsters will always be targetable. [default: false]
#   box - settings for the boxtrap action
#     material-id - block that the box will be made of [default: 1]
#     torch - add a torch/light above the player? [default: true]
#   hounds - settings for the hellhounds action
#     attack-delay - how long to wait before releasing the hounds on the player [default: 60]
#     removal-delay - how long before the hounds are marked for removal [default: 600]
# policies:
#   gamemode - whether or not the gamemode policies are enabled. [default: false]
# misc:
#   catch-moving-too-quickly-kick - prevents players from getting kicked for moving too quickly [default: false]

version: 1.1.0
override: true
debug: false
metrics-enabled: true
show-metrics-notice: true
save-ban-delay: 6000
save-ban-period: 36000
save-whitelist-delay: 18000
save-whitelist-period: 72000
session-prune-delay: 6000
session-prune-period: 12000
session-prune-epsilon: 3
wand-id: 369
whitelist-handler: true
database:
    driver: org.sqlite.JDBC
    url: jdbc:sqlite:{DIR}/{NAME}.db
    username: captain
    password: narwhals
    isolation: SERIALIZABLE
    logging: false
    rebuild: true
whitelisting:
    broadcast-failures: true
    print-on-load: true
    denial-message: You are not whitelisted on this server!
auth:
    require: true
    password-security: basic
    greet-players: true
    hide-inventory: false
    freeze-actions:
        chat: true
        commands: true
        drop: true
        interact: true
        block-interact: true
        block-place: true
        block-break: true
        movement: false
        teleport: true
actions:
    verbose-list: false
    ban:
        kick: true
    boom:
        power: 2.0
        fire: false
        animal-cruelty: false
        golem-cruelty: false
    box:
        material-id: 1
        torch: true
    hounds:
        attack-delay: 60
        removal-delay: 600
misc:
    catch-moving-too-quickly-kick: false