# version:
#   this specifies what version the config is set to, used for internal checks [DO NOT TOUCH]
# override:
#   this options basically tells openauth that it can override bukkit's internal whitelisting and etc. [default: true]
# debug:
#   this tells openauth whether or not to print extra debug messages [default: false]
# save-ban: (ban saving)
#   delay - how long to wait before starting to save bans [default: 6000 == 5 minutes]
#   period - how long to go in between running the ban saving task [default: 36000 == 30 minutes]
# save-whitelist: (whitelist saving)
#   delay - how long to wait before starting to save the whitelist [default: 18000 == 15 minutes]
#   period - how long to go in between running the whitelist saving task [default: 72000 == 60 minutes/1 hour]
# session-prune: (player session pruning)
#   delay - how long to wait before starting the pruning task [default: 6000 == 5 minutes]
#   period - how long to go in between running the task [default: 12000 == 10 minutes]
# wand-id:
#   this is the id of the admin wand item [default: 369 (blaze rod)]
# login-handler, whitelist-handler: (handler types {default (or on), off, extended})
#   default (or on) - uses the default handler for that action
#   off - turns off the handler
#   extended - modified 'default' state, allows setting of the handler by an outside plugin
#     for say, a plugin that extends this one by providing a separate set of handlers
# whitelisting:
#   broadcast-failures - when an unwhitelisted player attempts to join, broadcast it to all players [default: true]
# auth:
#   require - whether auth is required to be able to play, if so, user
#             will be frozen [default: true]
#   freeze-actions - actions that the player takes that will be
#                    frozen.
#     chat - freeze chat? [default: true]
#     interact - freeze all player interactions? [default: true]
#     block-interact - freeze all block interactions? [default: true]
#     block-place - freeze all block placements? [default: true]
#     block-break - freeze all block breaks? [default: true]
#     movement - freeze all player movement? [default: false]
#     teleport - freeze player teleportation? [default: true]
# actions:
#   ban - settings for the ban action
#     kick - whether or not to kick the user when the ban action is used [default: true]
#   boom - settings for the boom action
#     fire - whether or not the explosion causes fire [default: false]
#     power - power of the explosion as a double [default: 2.0]
#     animal-cruelty - allows(true)/disallows(false) targeting of animals (cows, sheep, pigs, etc..)
#                        monsters will always be targetable. [default: false]
#     golem-cruelty - allows(true)/disallows(false) targeting of golems (snowmen, iron golems..)
#                        monsters will always be targetable. [default: false]

version: 1.0
override: true
debug: false
save-ban-delay: 6000
save-ban-period: 36000
save-whitelist-delay: 18000
save-whitelist-period: 72000
session-prune-delay: 6000
session-prune-period: 12000
wand-id: 369
login-handler: default
whitelist-handler: default
whitelisting:
    broadcast-failures: true
auth:
    require: true
    freeze-actions:
        chat: true
        interact: true
        block-interact: true
        block-place: true
        block-break: true
        movement: false
        teleport: true
actions:
    ban:
        kick: true
    boom:
        power: 2.0
        fire: false
        animal-cruelty: false
        golem-cruelty: false