name: OpenAuth
main: me.maiome.openauth.bukkit.OpenAuth
version: 1.0.0
authors: ['pirogoeth', 'TakSayu']
depend: ['WorldEdit']
softdepend: ['PermissionsEx', 'bPermissions', 'PermissionsBukkit', 'Permissions', 'JSONAPI']
load: startup
hashtag: 8f235b5
hashtag: 8f235b5